# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

#作者：Tioks0
#链接：https://juejin.im/post/5ba22293e51d450e46282d68
#来源：掘金
#著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
# 解决xcode10对版本号警告的问题.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end

#target 'Ycsj' do

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# 忽略pod第三方库文件警告
inhibit_all_warnings!


target 'PoporUploadVC_Example' do
  pod 'PoporUploadVC', :path => '../'

  target 'PoporUploadVC_Tests' do
    inherit! :search_paths

    
  end
end
